const ClientRoutes = {
    home: '/',
    about: '/about',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    changePassword: '/change-password',
    contact: '/contact',
    menu: '/menu',
    service: '/service',
    booking: '/booking',
    detailproduct: '/product-detail/:slug.html',
    account: '/account',
    blog: '/blog',
    detailblog: '/blog-detail/:slug.html',
    order: '/order',
    pay: '/pay',
    confirm: '/confirm',
    policy: '/policy',
    reservationGuide: '/reservation-guide',
    commentBlog: 'comment-blog',
    commentBlogAdd: 'comment-blog/add',
    myBookings: '/my-bookings',
};

export default ClientRoutes;
